#[derive(Copy, Clone, Eq, PartialEq, Ord, PartialOrd, Debug)]
pub enum Rythm {
    Sixteenth, // 𝅘𝅥𝅯
    Eighth,    // 𝅘𝅥𝅮
    Quarter,   // 𝅘𝅥
    Half,      // 𝅗𝅥
    Whole,     // 𝅝
    Double,    // 𝅜
}
